Log unknown atoms instead of (sometimes) returning an error. (#84)
* Log unknown atoms instead of returning an error.

We should enable this for unit tests, but currently the hevc test would
fail. I don't want to create a feature flag until there's test coverage.

cargo test --features strict

---- test::hevc::hevc stdout ----

thread 'test::hevc::hevc' panicked at src/test/hevc.rs:214:34:
failed to decode moov: UnexpectedBox(fiel)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Alternatively, we could use `tracing_test` to ensure that none of the
unit tests have log output. That might be cleaner if we don't want a
feature flag in the future.

* Simplify.

* Also log the parent atom.